name: Docker Image CI

on:
  push:
    branches: ["thebizapi"]
  pull_request:
    branches: ["thebizapi"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build the Docker image
      run: |
        # /usr/bin/git config --list --global
        # curl -s "https://get.sdkman.io" | bash
        # source "/home/runner/.sdkman/bin/sdkman-init.sh"
        # sdk install java 11.0.24-tem
        # sed -i 's/github-ssh/github/' myaddons.xml
        ./gradlew getRu getComponentSet -PcomponentSet=thebizapi dOS addRu
        # cd docker/simple
        # ./docker-build.sh ../.. thebizapi/thebizapi:$(date +%s)
