name: Docker Image CI

on:
  push:
    branches: ["thebizapi"]
  pull_request:
    branches: ["thebizapi"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0


    - name: Build the Docker image
      run: |
        eval "$(ssh-agent -s)"
        echo "${{ secrets.PRIVATE_SSH_KEY }}" > id_ed25519
        chmod 600 id_ed25519
        ssh-add id_ed25519
        ./gradlew getRu getCompSet -PcomponentSet=thebizapi dOS addRu
        cd docker/simple
        ./docker-build.sh ../.. thebizapi/thebizapi:$(date +%s)
